export const movieList = [
  { name: 'The Shawshank Redemption' },
  { name: 'The Godfather' },
  { name: 'The Dark Knight' },
  { name: '12 Angry Men' },
  { name: 'The Lord of the Rings: The Return of the King' },
  { name: 'Pulp Fiction' },
  { name: 'Fight Club' },
  { name: 'The Lord of the Rings: The Fellowship of the Ring' },
  { name: 'Forrest Gump' },
  { name: 'Inception' },
  { name: 'The Empire Strikes Back' },
  { name: 'The Matrix' },
  { name: 'Goodfellas' },
  { name: 'The Silence of the Lambs' },
  { name: 'Saving Private Ryan' },
  { name: 'The Green Mile' },
  { name: 'Interstellar' },
  { name: 'Psycho' },
  { name: 'The Departed' },
  { name: 'Whiplash' },
  { name: 'Gladiator' },
  { name: 'The Prestige' },
  { name: 'Back to the Future' },
  { name: 'Raiders of the Lost Ark' },
  { name: 'Rear Window' },
  { name: 'The Lion King' },
  { name: 'American History X' },
  { name: 'Apocalypse Now' },
  { name: 'Alien' },
  { name: 'The Great Dictator' },
  { name: 'Django Unchained' },
  { name: 'The Shining' },
  { name: 'WALL·E' },
  { name: 'Avengers: Infinity War' },
  { name: 'Dr. Strangelove' },
  { name: 'Joker' },
  { name: 'Witness for the Prosecution' },
  { name: 'Citizen Kane' },
  { name: 'Braveheart' },
  { name: 'Vertigo' },
  { name: 'North by Northwest' },
  { name: 'Star Wars: A New Hope' },
  { name: 'Memento' },
  { name: 'Raging Bull' },
  { name: 'Aliens' },
  { name: 'Avengers: Endgame' },
  { name: 'A Clockwork Orange' },
  { name: 'Taxi Driver' },
  { name: 'Amadeus' },
  { name: 'Eternal Sunshine of the Spotless Mind' },
  { name: 'Full Metal Jacket' },
  { name: 'A Space Odyssey' },
  { name: 'Toy Story' },
  { name: 'The Sting' },
  { name: 'Reservoir Dogs' },
  { name: 'The Apartment' },
  { name: 'L.A. Confidential' },
  { name: 'The Big Lebowski' },
  { name: 'The Deer Hunter' },
  { name: 'Die Hard' },
  { name: 'Heat' },
  { name: 'Batman Begins' },
  { name: 'Unforgiven' },
  { name: 'Blade Runner' },
  { name: 'The Grand Budapest Hotel' },
  { name: 'Lock, Stock and Two Smoking Barrels' },
  { name: 'Scarface' },
  { name: 'The Elephant Man' },
  { name: 'Trainspotting' },
  { name: 'The Sixth Sense' },
  { name: 'The Thing' },
  { name: 'No Country for Old Men' },
  { name: 'Finding Nemo' },
  { name: 'Snatch' },
  { name: 'Kill Bill: Vol. 1' },
  { name: 'Chinatown' },
  { name: 'The Wolf of Wall Street' },
  { name: 'Room' },
  { name: 'Shutter Island' },
  { name: 'The Revenant' },
  { name: 'Jurassic Park' },
  { name: 'The Night of the Hunter' },
  { name: 'The General' },
  { name: 'Spotlight' },
  { name: 'Mad Max: Fury Road' },
  { name: 'Cool Hand Luke' },
  { name: 'Rebecca' },
  { name: 'Gone with the Wind' },
  { name: 'Into the Wild' },
  { name: 'Warrior' },
  { name: 'It Happened One Night' },
  { name: 'Life of Brian' },
  { name: 'Network' },
  { name: 'La La Land' },
  { name: 'Logan' },
  { name: 'There Will Be Blood' },
  { name: 'Stand by Me' },
  { name: 'Platoon' },
  { name: 'Ben-Hur' },
  { name: 'Donnie Darko' },
  { name: '12 Years a Slave' },
  { name: 'Hotel Rwanda' },
  { name: 'Casino' },
  { name: 'Butch Cassidy and the Sundance Kid' },
  { name: 'Guardians of the Galaxy' },
  { name: 'Before Sunrise' },
  { name: 'The Princess Bride' },
  { name: 'The Best Years of Our Lives' },
  { name: 'In the Name of the Father' },
  { name: 'Mary and Max' },
  { name: 'Prisoners' },
  { name: 'The Grapes of Wrath' },
  { name: 'Catch Me If You Can' },
  { name: 'Gandhi' },
  { name: 'Monsters, Inc.' },
  { name: 'The Terminator' },
  { name: 'Groundhog Day' },
  { name: 'The Bourne Ultimatum' },
  { name: 'The Wizard of Oz' },
  { name: 'Jaws' },
  { name: 'Dead Poets Society' },
  { name: 'The Miracle Worker' },
  { name: 'The Truman Show' },
  { name: 'The Manchurian Candidate' },
  { name: 'Barry Lyndon' },
  { name: 'The Last Picture Show' },
  { name: 'Rocky' },
  { name: 'Dog Day Afternoon' },
  { name: 'The Imitation Game' },
  { name: 'Stalker' },
  { name: 'Inglourious Basterds' },
  { name: 'Rush' },
  { name: 'Nightcrawler' },
  { name: 'Rain Man' },
  { name: 'The Straight Story' },
  { name: 'The Handmaiden' },
  { name: 'Gangs of Wasseypur' },
  { name: 'Guardians of the Galaxy' },
  { name: 'Prisoners' },
  { name: 'Catch Me If You Can' },
  { name: 'Groundhog Day' },
  { name: 'The Manchurian Candidate' },
  { name: 'Barry Lyndon' },
  { name: 'The Last Picture Show' },
  { name: 'Dog Day Afternoon' },
  { name: 'The Imitation Game' },
];

